# Generated by Django 4.1.10 on 2023-08-30 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_category_post_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category_id',
            new_name='category',
        ),
    ]
