# Generated by Django 4.1.10 on 2023-08-22 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_remove_hashtag_post_remove_hashtag_writer_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HashTag',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='hashtags',
            new_name='tags',
        ),
    ]
