# Generated by Django 4.1.10 on 2023-08-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_rename_hashtag_tag_rename_hashtags_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.TextField(max_length=255, unique=True),
        ),
    ]
