# Generated by Django 4.1.10 on 2023-09-01 00:43

from django.conf import settings
from django.db import migrations, models
import mysite.json_extended


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_roommember_delete_roomuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roommember',
            old_name='member',
            new_name='user',
        ),
        migrations.AddField(
            model_name='room',
            name='online_user_set',
            field=models.ManyToManyField(blank=True, related_name='joined_room_set', through='chat.RoomMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='roommember',
            name='channel_names',
            field=models.JSONField(decoder=mysite.json_extended.ExtendedJSONDecoder, default=set, encoder=mysite.json_extended.ExtendedJSONEncoder),
        ),
    ]
