# Generated by Django 4.1.10 on 2023-09-02 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_rename_category_id_post_category'),
        ('chat', '0006_rename_member_roommember_user_room_online_user_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='post',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='post.post'),
            preserve_default=False,
        ),
    ]
