# Generated by Django 4.1.10 on 2023-08-31 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
