# Generated by Django 4.1.10 on 2023-09-01 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userprofile_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
